---
title: "question_3"
author: "Sarahy Martinez"
output: github_document
---


```{r setup, include=FALSE}

library(tidyverse)
library(dplyr)
library(lubridate)

```

```{r}
# read in the dataset 

ccu_data =
   read_csv(
  "C:/Users/sarah/OneDrive/Documents/Data Science/clinical/202210 - EDW - CCU_assessment.csv",
  na = c("NA", ".", "")
) %>% 
  janitor::clean_names() %>% 
  select(mrn_hidden, enc_no_hidden,adt_evnt_nm,from_dept, adt_dttm_hidden,to_dept)
  
```


Recoding data from the notes regarding:

```{r, message=FALSE}

updated_data = ccu_data %>% 
    mutate(adt_dttm = mdy_hm(adt_dttm_hidden)) %>% #mutate adt so that date time are more legible
    group_by(mrn_hidden, enc_no_hidden) %>%  #grouping by id since its the common identifier and instructions say to group by both variables
   arrange(adt_dttm) %>%  # arranging the admitted dates and times for order 
  summarise(
    first_icu_admission = min(adt_dttm[grepl("ICU", to_dept)], na.rm = TRUE), #min for the first encounter in the icu admin date
    first_icu_discharge = min(adt_dttm[grepl("ICU", from_dept)], na.rm = TRUE), # min for the first icu discharge 
    .groups = "drop" 
  ) %>%
  mutate(
    first_icu_discharge = if_else(is.infinite(first_icu_discharge),
                                  ymd_hms("2022-10-03 00:00:00"), # for anyone admitted ansd is still there will use this discharge date
                                  first_icu_discharge),
    first_icu_los = as.numeric(difftime(first_icu_discharge,   # use sql diff time to calculate the length of stay between admin and discharge and want in hrs
                                        first_icu_admission,
                                        units = "hours")))

# under first_icu_admission some values will appear inf that s
```

