---
title: "question2_clinical"
author: "Sarahy Martinez"
output: github_document
---

```{r}
# to create the sankey diagram we need to install the remotes package and githbut package 
#install.packages("remotes")
#remotes::install_github("davidsjoberg/ggsankey")

```

```{r}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(hexbin)
library(patchwork)
library(readxl)
library(ggsankey)
library(ggplot2)
library(dplyr) 

theme_set(theme_minimal()+ theme(legend.position = "bottom"))

options(
  
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_fill_discrete = scale_fill_viridis_d()    

scale_colour_discrete = scale_fill_viridis_d() 


```


```{r}
#read in the dataset and rename columns so it's easier to tidy later

stacked_data = read_excel("C:/Users/sarah/OneDrive/Documents/Data Science/clinical/Stacked_column_stroke_blacks_noAF.xlsx",
                           na = c("NA", ".", "")) %>% 
   rename(
    year_1990 = `1990`,
    year_1995 = `1995`,
    year_2000 = `2000`,
    year_2005 = `2005`,
    year_2010 = `2010`
  ) %>%
   janitor::clean_names()
```

```{r}

# tidy the data so that we have a column for just one year variable and not multiple 

stacked_data_tidy = 
  pivot_longer(
    stacked_data, 
    year_1990:year_2010,
    names_to = "year",    
    names_prefix = "year_", 
    values_to = "PopulationAttributableRisk") %>% 
   mutate(year = as.numeric(year)) %>%  # changed from character to numeric so year can be treated as value
   janitor::clean_names() # clean names so that variable names follow better naming conventions
                                
#pivot longer will make it easier to graph the risk factors and years separately 



```

# Plots 

## Plot with white space 

```{r}


ggplot(stacked_data_tidy, aes(x = year, 
                              y = population_attributable_risk, 
                              fill = risk_factors_for_stroke_in_blacks)) +
  geom_area(color = "white", size = 2, alpha = 0.95) +
  scale_fill_manual(values = c(
    "Diabetes" = "#D55E00",
    "Hypercholesterolemia" = "#E69F00",
    "Hypertension" = "#009E73",
    "Obesity" = "#56B4E9",
    "Smoking" = "#7B68EE"
  ),
name = NULL)+
  scale_x_continuous(breaks = seq(190, 2010, 5)) +
  labs(
    title = " Risk Contributors to Stroke in Blacks ",   # <-- now at top
    y = "Population Attributable Risk",                                
    x = "Year"
  ) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5) # centered title
  )



```


## Plot without whitespace 

```{r}


ggplot(stacked_data_tidy, aes(x = year, 
                              y = population_attributable_risk, 
                              fill = risk_factors_for_stroke_in_blacks)) +
  geom_area(color = "white", size = 0, alpha = 0.95) +
  scale_fill_manual(values = c(
    "Diabetes" = "#D55E00",
    "Hypercholesterolemia" = "#E69F00",
    "Hypertension" = "#009E73",
    "Obesity" = "#56B4E9",
    "Smoking" = "#7B68EE"
  ),
name = NULL)+
  scale_x_continuous(breaks = seq(190, 2010, 5)) +
  labs(
    title = " Risk Contributors to Stroke in Blacks ",   # <-- now at top
    y = "Population Attributable Risk",                                
    x = "Year"
  ) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5) # centered title
  )


```


Using ggsankey

```{r}
# converting data so it can align with the sankey graph
sankey_data = stacked_data_tidy %>%
  mutate(year = as.character(year)) %>%
  make_long(year, risk_factors_for_stroke_in_blacks)


sankey_temp <- sankey_data %>%
  left_join(
    stacked_data_tidy %>% mutate(year = as.character(year)),
    by = c("x" = "year", "node" = "risk_factors_for_stroke_in_blacks")
  ) %>%
  mutate(value = ifelse(is.na(population_attributable_risk), 1, population_attributable_risk)) %>%
  select(-population_attributable_risk)


ggplot(sankey_temp,
       aes(x = x,
           next_x = next_x,
           node = node,
           next_node = next_node,
           fill = node,
           value = value)) +
  geom_sankey(flow.alpha = 0.9, node.color = "white") +
  scale_fill_manual(values = c(
    "Diabetes" = "#D55E00",
    "Hypercholesterolemia" = "#E69F00",
    "Hypertension" = "#009E73",
    "Obesity" = "#56B4E9",
    "Smoking" = "#7B68EE"
  ), name = NULL) +
  labs(
    title = "Risk Contributors to Stroke in Blacks",
    x = "Year",
    y = "Population Attributable Risk"
  ) +
  theme_sankey(base_size = 14) +
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5)
  )


```
``
